### ISSUE TITLE
'C44 Other malignant neoplasms of skin' is Charlson Index comorbidity?

### ISSUE THREAD

**Issue by hemagi** [bjoroeKI/Charlson-comorbidity-index-revisited#2]
Hi,

according to table 1 at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7812935/ the diagnosis

C44 Other malignant neoplasms of skin

it not part of the cancer group.

According to the code in this repository C44 counts as cancer.

So what is right?

**Comment by bjoroeKI** [comment]
Hi Marcus,

We are working on a new version of the code, based on input from users. C44 is one of the codes that will be dropped in the next version.

Bjorn

From: Marcus ***@***.***>
Sent: den 20 februari 2023 11:46
To: bjoroeKI/Charlson-comorbidity-index-revisited ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bjoroeKI/Charlson-comorbidity-index-revisited] 'C44 Other malignant neoplasms of skin' is Charlson Index comorbidity? (Issue #2)


Hi,

according to table 1 at https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7812935/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fpmc%2Farticles%2FPMC7812935%2F&data=05%7C01%7Cbjorn.roelstraete%40KI.se%7Ce173049991644c685a0608db132f969d%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638124867328249568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BSZysmJvdXs8tj094%2BKlrIE7h04N0UiiSTdUxa2ybYg%3D&reserved=0> the diagnosis

C44 Other malignant neoplasms of skin

it not part of the cancer group.

According to the code in this repository C44 counts as cancer.

So what is right?

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FbjoroeKI%2FCharlson-comorbidity-index-revisited%2Fissues%2F2&data=05%7C01%7Cbjorn.roelstraete%40KI.se%7Ce173049991644c685a0608db132f969d%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638124867328249568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BV3o3tR3P%2B5Vn3AqAoTN6dz2SfFLtD5f%2Bk2jMiOQJag%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAR2OJ4N45VZGSMODYXKP33LWYNDMVANCNFSM6AAAAAAVBWZPPM&data=05%7C01%7Cbjorn.roelstraete%40KI.se%7Ce173049991644c685a0608db132f969d%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C638124867328249568%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EJFJCB%2B%2BrIcn3Z%2BhmmRQCaL5zjaR%2F6jMsvEQw2Y4Q6I%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>



N?r du skickar e-post till Karolinska Institutet (KI) inneb?r detta att KI kommer att behandla dina personuppgifter. H?r finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI's processing of personal data here<https://ki.se/en/staff/data-protection-policy>.
